name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치로 푸시될 때 동작

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # 배포 디렉토리로 이동
          cd /home/ubuntu/project
          # 최신 코드 가져오기
          git pull origin main
          # Node.js 의존성 설치 및 서버 재시작
          cd my-node-app
          npm install
          pm2 restart app.js
          # Flask 서버 관리
          cd ../flask_server
          source venv/bin/activate
          pip install -r requirements.txt
          pm2 restart flask-server
